# http://wiki.ros.org/laser_filters

scan_filter_chain:
- name: range_filter
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.2
    upper_threshold: 2.0
    lower_replacement_value: 0
    upper_replacement_value: .inf
- name: angular_bounds_filter
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.5707
    upper_angle: 1.5707